version: '3.9'
services:
  backend:
    image: node:16.14
    container_name: app_backend
    build: ./
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    platform: linux/x86_64
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/ng_cash?schema=public
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
  db:
    image: postgres:13
    container_name: db
    volumes:
      - ./:/app
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    restart: 'always'