version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
  db:
    image: postgres:13
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    restart: 'always'